# Generated by Django 3.0.7 on 2020-07-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('emial', models.EmailField(max_length=50)),
                ('contact', models.IntegerField()),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
