# Generated by Django 3.0.7 on 2020-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200709_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolleddetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Studentcontact', models.IntegerField(unique=True)),
                ('CourseID', models.IntegerField()),
            ],
        ),
    ]
