# Generated by Django 3.0.7 on 2020-07-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_enrolleddetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolleddetails',
            name='id',
        ),
        migrations.AddField(
            model_name='enrolleddetails',
            name='idno',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scheduleclass',
            name='duration',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
