# Generated by Django 3.0.7 on 2020-07-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200715_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolleddetails',
            name='idno',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
