# Generated by Django 3.0.7 on 2020-07-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200715_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolleddetails',
            name='Studentcontact',
            field=models.IntegerField(default=True),
        ),
    ]
