# Generated by Django 3.0.7 on 2020-07-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200715_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolleddetails',
            name='idno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
